name: query_signals
description: A comprehensive signals toolkit for Flutter with persistence, queries, and state management
version: 0.1.1
homepage: https://github.com/davidhavlin/query_signals

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  signals: ^6.0.2
  path_provider: ^2.1.2
  path: ^1.8.3
  source_gen: ^2.0.0
  build: ^2.5.4
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

flutter:
